### PR TITLE
Docs + updated files layout + cleanup

### PR DESCRIPTION
**Pull request by ChGen**
Updated directories/files layout to store different repositories in more structured and predictable form. 
Part of https://github.com/artipie/benchmarks/issues/59
Remove redundant files.
Updated README.md. 
Repository test data structure is shown in `README.md##Test data structure`

### CODE REVIEW

**Comment by ChGen** [comment]
@dgarus , please review

**Comment by ChGen** [comment]
@olenagerasimova , please review

**Review by Swizbiz — APPROVED** [review]
LGTM, thank you!

**Review by olenagerasimova — APPROVED** [review]
@ChGen thanks

**Pull request merged**
