### PR TITLE
Performance testing scripts + readme

### PR DESCRIPTION
**Pull request by ChGen**
Performance testing scripts + readme. Part of https://github.com/artipie/benchmarks/issues/64

Scripts will be used by CI pipeline mostly.
- `perfplot.py` - generates `.svg`` graph files with tables for performance data.
- `sync_perftests.sh` - download and upload performance data files. Currently, `central.artipie.com` is used ad performance data storage.

### CODE REVIEW

**Comment by ChGen** [comment]
@dgarus , please review

**Review by olenagerasimova — CHANGES_REQUESTED** [review]
@ChGen thank, all looks good, the only suggestion is to clean the scripts from comments (like some prints)

**Comment by ChGen** [comment]
I cleaned-up some parts,  few still left and will be removed on the later stage of development.

**Comment by ChGen** [comment]
@olenagerasimova , please review

**Review by olenagerasimova — APPROVED** [review]
thanks

**Review by dgarus — APPROVED** [review]
thanks!

**Pull request merged**
