### PR TITLE
feat: plot charts for benchmarks results

### PR DESCRIPTION
**Pull request by genryxy**
Part of artipie/artipie#431
Added script for plotting charts for benchmarks results

### CODE REVIEW

**Comment by genryxy** [comment]
Example of charts are below

**Review by g4s8 — CHANGES_REQUESTED** [review]
@genryxy looks great! But how these images will be added to benchmarks page? I think we need some target in Makefile to add it, e.g.:
```makefile
draw_plots: <results>
  python3 ./scriptfile.py ./benchmraks/path-to-doc.md
```

**Comment by genryxy** [comment]
@g4s8 I thought to add one more step to this [script](https://github.com/artipie/helm-adapter/blob/master/.github/workflows/benchmarks.yml#L26). Something like this:
```yml
          cp -avr out/${{ env.REPO }}/* $GITHUB_WORKSPACE/benchmarks/results/${{ env.TAG }}
          cd ../..
      - name: Add results to README
        run: |
          # probably here also `pip install matplotlib` 
          python benchmarks/scripts/writeresults.py ${{ env.TAG }}
          python benchmarks/scripts/charts.py number-charts-to-plot
          rm -rf tmp-bench
```

**Comment by g4s8** [comment]
> @g4s8 I thought to add one more step to this [script](https://github.com/artipie/helm-adapter/blob/master/.github/workflows/benchmarks.yml#L26). Something like this:
> 
> ```yaml
>           cp -avr out/${{ env.REPO }}/* $GITHUB_WORKSPACE/benchmarks/results/${{ env.TAG }}
>           cd ../..
>       - name: Add results to README
>         run: |
>           # probably here also `pip install matplotlib` 
>           python benchmarks/scripts/writeresults.py ${{ env.TAG }}
>           python benchmarks/scripts/charts.py number-charts-to-plot
>           rm -rf tmp-bench
> ```

@genryxy but then we need to add it to each adapter and it'll be not consistent with other steps of benchmark. Using Makefile we can hide this boilerplate code and use common dependencies for that, e.g. `make draw-graph` will depend on benchmarks running and can run it automatically and copy all results to correct directories. So we can call only one command from actions workflow file to perform all steps in one command.

**Comment by genryxy** [comment]
@g4s8 could you please check this one

**Comment by g4s8** [comment]
> @g4s8 could you please check this one

@genryxy can you please answer or fix my last comment here https://github.com/artipie/benchmarks/pull/39#issuecomment-972582577

**Comment by genryxy** [comment]
@g4s8 I add this step to make in [this](https://github.com/artipie/benchmarks/pull/38/files#diff-700ffcc93c1d9fd96a52c71997eb97c098b4ec98ca0c1c2931348d985f82ea2eR36) PR. One for writing results to the file and another step for plotting graphics

**Review by g4s8 — APPROVED** [review]
@genryxy got it, thanks

**Pull request merged**
